module.exports = {
  SUCCESS: "Success",
  BRANCH_NOT_FOUND: "Branch Not Found",
  ACCOUNT_NOT_FOUND: "Account Not Found",
  USER_NOT_FOUND: "User Not Found",
  USER_ALREADY_EXISTS: "Email/UserName Already Exists",
  USER_LOGIN_SUCCESS: "Logged In Successfully",
  USER_REGISTER_SUCCESS: "User Registered Successfully",
  ADMIN_VERIFICATION_PENDING:
    "Email/UserName Exists, Admin Verification Pending",
  BAD_CREDENTAILS: "Email/Password not matched",
  PASSWORD_CONFIRMPASSWORD: "Password and Confirmed Password does not match",
  SOMETHING_ERROR_OCCURRED: "Something Error Occurred",
  USER_DOESNOT_EXISTS: "User Does Not Exists",
  JWT_SIGN_ERROR: "Error while signing JWT Error",
  SESSION_ALREADY_EXISTS: "Session Already Exists, Please Logout",
  OTP_SENT_SUCCESSFULLY: "OTP Sent to Email Successfully",
  OTP_VERIFIED_SUCCESSFULLY: "OTP Verification Successfull",
  OTP_INVALID: "OTP is Invalid/Expired",
  OTP_EXISTS: "OTP ALREADY SENT. Please Verify/Resend after sometime",
  EMAIL_SENT_SUCCESSFULLY: "Email Sent Successsfully",
  RESET_LINK_EXISTS:
    "Reset Link Already Exists. Please Reset/Resend after sometime",
  USER_ALEADY_VERIFIED: "User Already Verified",
  EMAIL_VERIFICATION_SUCCESS: "Email Verified Successfully",
  INVALID_RESET_LINK: "Reset Link Invalid Or Expired",
  PASSWORD_UPDATED: "Password Updated Successfully. Please login",
  SESSION_EXPIRED: "Session TimeOut/Expired. Please login again",
  TOKEN_EXPIRED: "Token Expired",
  UNAUTHORIZED_ACCESS: "Token Invalid/Unauthorized Access",
  EMAIL_TAKEN: "Email Already Taken",
  USERNAME_TAKEN: "User Name already Taken",
  PHONE_TAKEN: "Phone Associated With Another Account",
  USER_LOGGED_OUT_SUCCESS: "User Logged Out Successfully",
  SESSION_DOESNOT_EXISTS: "Session Not Found",
  INVALID_LOGOUT_LINK: "Logout Link Invalid/ Already LoggedOut",
  PROVIDE_TOKEN: "Please provide token to authorize",
  UNAUTHORIZED_ACCESS_TOKEN: "Token is Invalid / Expired",
  DATA_NOT_FOUND: "Data Not Found",
  DATA_UPDATED_SUCCESS: "Data Updated Successfully",
  PROVIDE_USERID: "Provide Appropriate UserId",
  USER_BLOCKED_BY_ADMIN:
    "Blocked By Admin, Please contact for more information",
  DATA_DELETED_SUCCESS: "Data Deleted Successfully",
  ID_NOT_PROVIDED: "Please Provide Valid Id",
  CREATE_PATIENT_CONFLICT:
    "Patient Aadhaar number or mobile number already exists",
  CREATE_GUARDIAN_CONFLICT: "Patient Guardian details already exists",
  FAILED_CREATING_PATIENT: "Failed Creating Patient. Please try again !",
  NO_PATIENT_FOUND: "No Patient Found",
  PATIENT_DOES_NOT_EXIST: "Patient with given Id does not exist",
  GUARDIAN_DOES_NOT_EXIST: "Guardian with given Id does not exist",
  VISIT_ALREADY_EXIST: "Active Visit Already Exist",
  VISIT_DOES_NOT_EXIST: "Given Visit Doesnt Exist",
  NO_ACTIVE_VISIT_EXIST: "No Active Visit Exist",
  VISIT_SUCCESSFULLY_UPDATED: "Visit Successfully Updated",
  DOCTORS_AVAILABILITY_ALREADY_SET:
    "Doctor Availability already created . Please Edit !",
  DOCTOR_AVAILABILITY_SUCCESSFULLY_UPDATED:
    "Doctor Availability Successfully Updated",
  DOCTOR_AVAILABILITY_DOESNOT_EXIST: "Doctor Availability doesnt existed",
  DOCTOR_AVAILABILITY_SUCCESSFULLY_DELETED:
    "Doctor Availability Successfully Deleted",
  SLOT_ALREADY_TAKEN: "Slot Already Taken, Please book another slot",
  SLOT_BOOKED_SUCCESS: "Appointment Booked Successfully",
  STAGE_DOES_NOT_EXISTS: "Invalid Stage Provided",
  INVALID_STAGE_OPERATION: "Invalid Operation from {source} to {destination}",
  APPOINTMENT_NOT_FOUND: "Appointment Not Found",
  PARAMS_ERROR: "Missing parameter: {params}",
  SHIFT_REQUEST_EXISTS: "Shift Request Already Exists",
  INVALID_OPERATION: "Operation Invalid for the User",
  TAX_CATEGORY_DOES_NOT_EXIST:
    "Tax Category details with given Id does not exist",
  INVENTORY_TYPE_DOES_NOT_EXIST:
    "Inventory Type details with given Id does not exist",
  SUPPLIER_DOES_NOT_EXIST: "Supplier details with given Id does not exist",
  MANUFACTURER_DOES_NOT_EXIST:
    "Manufacturer details with given Id does not exist",
  ORDER_DETAILS_DOES_NOT_EXIST: "Orders details with given Id does not exist",
  PAYMENT_SUCCESSFUL: "payment successful",
  PAYMENT_DETAILS_NOT_FOUND: "Payment details not found",
  GRN_PAYMENT_SUCCESSFULLY_SAVED: "Grn Payment Successfully saved",
  SUB_CATEGORY_ALREADY_EXISTS: "SubCategory Already Exists",
  TREATMENT_NOT_FOUND: "Treatment Does not Exists",
  TREATMENT_ALREADY_EXISTS_FOR_THIS_VISIT:
    "Treatment Already Exists for this Visit",
  UNAUTHORIZED_FOR_STAGE_OPERATION: "Cannot Modify Stage. Unauthorized Access",
  UNAUTHORIZED_WITHOUT_VITALS: "Cannot move further without vitals",
  EMBRYOLOGY_RECORD_NOT_FOUND: "Embryology Record Not found",
  CONSULTATION_FEE_ERROR:
    "Consultation Fee Expired/Please Pay Consultation Fee",
  PACKAGE_ALREADY_EXIST_FOR_VISIT: "Package Already Exists for Visit",
  PACKAGE_NOT_FOUND: "Package Not Found with given Id",
  PACKAGE_UPDATED_SUCCESSFULLY: "Package Updated Successfully",
  VITALS_ALREADY_EXISTS: "vitals already exists for this appointment",
  VITALS_DOESNOT_EXISTS: "vitals does not exists",
  DELETED_SUCCESSFULLY: "deleted Successfully",
  REGISTRATION_FEE_NOT_PAID: "Registration Fee Not Paid",
  ICSI_CONSENTS_DOES_NOT_EXISTS: "ICSI Consents Does Not Exists",
  IUI_CONSENTS_DOES_NOT_EXISTS: "IUI Consents Does Not Exists",
  ICSI_ALREADY_STARETD: "ICSI Already Started",
  IUI_ALREADY_STARETD: "IUI Already Started",
  OITI_ALREADY_STARETD: "OITI Already Started",
  ICSI_NOT_ALREADY_STARETD: "ICSI Not Already Started",
  IUI_NOT_ALREADY_STARETD: "IUI Not Already Started",
  OITI_NOT_ALREADY_STARETD: "OITI Not Already Started",
  FET_NOT_ALREADY_STARETD: "FET Not Already Started",
  FET_CANNOT_BE_STARTED: "FET Does Not Exists For this Treatment",
  TRIGGER_STARTED_SUCCESSFULLY: "Trigger Started Successfully",
  UNAUTHORIZED_FOR_STAGE_OPERATION_PAYMENT:
    "Payment Pending/Due date Reached. Cannot move to Next Stage",
  TOTAL_AMOUNT_IS_LESS: "Complete Amount Should be Paid",
  FET_CONSENTS_DOES_NOT_EXISTS: "FET Consents Does not Exists",
  FET_ALREADY_STARTED: "FET Already Started",
  FET_NOT_ALREADY_STARTED: "FET Not Already Started",
  ERA_CONSENTS_DOES_NOT_EXISTS: "ERA Consents Does not Exists",
  ERA_ALREADY_STARTED: "ERA Already Started",
  ERA_NOT_ALREADY_STARTED: "ERA Not Already Started",
  DISCOUNT_APPLIED_SUCCESSFULLY: "Discount Applied Successfully",
  DISCOUNT_ALREADY_APPLIED: "Discount Already Applied",
  DISCOUNT_AMOUNT_SHOULD_BE_LESS:
    "Discount Amount should be less than all stage amounts",
  UNAUTHORIZED_FOR_APPLYING_DISCOUNT: "you are not allowed to apply discount",
  COUPON_NAME_EXISTS: "Coupon Code with Same Name Already Exists",
  COUPON_DOES_NOT_EXISTS: "Coupon Does Not Exists",
  PAYABLE_AMOUNT_AFTER_DISCOUNT_WRONG:
    "Payable Amount after discount was provided wrong",
  PAYABLE_AMOUNT_WRONG: "Payable Amount was provided wrong",
  CONSULTATION_NOT_FOUND_FOR_VISIT: "No Consultations Found for this Visit",
  TREATMEMT_NOT_FOUND_FOR_VISIT: "No Treatment Found for this Visit",
  UNAUTHORIZED_FOR_APPOINMENT_DELETION: "UnAuthorized for Appointment Deletion",
  APPOINTMENT_DELETION_STAGE: "Appointment Cannot Be Deleted At this Stage",
  APPOINTMENT_DELETION_PAYMENT:
    "Appointment Cannot Be Deleted, Payment Exists For this Appointment",
  APPOINTMENT_REASON_EXISTS: "Appointment Reason Already Exists",
  APPOINTMENT_ALREADY_BOOKED:
    "Patient Appointment Already Booked For this slot",
  SAVE_DONAR_CONFLICT: "Donar already exists",
  LAB_TEST_GROUP_EXISTS: "Lab Test Group Already Exists",
  SAMPLE_TYPE_EXISTS: "Lab Test Sample Type Already Exists",
  LAB_TEST_NAME_EXISTS: "Lab Test Already Exists",
  SCAN_NAME_EXISTS: "Scan Name Already Exists",
  EMBRYOLOGY_NAME_EXISTS: "Embryology Name Already Exists",
  SAME_MEDICATION_NAME_EXISTS: "Medication Name Already Exists",
  PENDING_PAYMENTS_FOR_VISIT_CLOSE:
    "Please complete pending Payments before closing Visit!",
  VISIT_CLOSED_SUCCESSFULLY: "Visit Closed Successfully",
  ITEM_NOT_FOUND: "Medication Item not found",
  NOSHOWAPPLIED_SUCCESSFULLY: "No Show Applied Successfully",
  INCIDENT_DETAILS_NOT_FOUND: "Incident Details Not Found",
  DEPARTMENT_NAME_EXISTS: "Department Name Already Exists",
  VENDOR_NAME_EXISTS: "Vendor Name Already Exists",
  SUPPLIES_NAME_EXISTS: "Supplies Name Already Exists",
  ORDER_NOT_FOUND: "Order Not Found",
  ORDER_PLACED_SUCCESSFULLY: "Order Placed Successfully",
  ORDER_RECEIVED_SUCCESSFULLY: "Order Received Successfully",
  ORDER_PAID_SUCCESSFULLY: "Order Paid Successfully",
  LAB_TEST_TEMPLATE_NOT_FOUND: "Lab Test Template Not Found",
  CANNOT_MOVE_COMPLETED:
    "Lab/Scan/Pharmacy/Embryology Pending. Cannot move to Completed",
  REFERRAL_NAME_EXISTS: "Referral Name Already Exists",
  CITY_NAME_EXISTS: "City Name Already Exists",
  TREATMENT_EXISTS_CLOSE_IN_TREATMENT:
    "Treatment Exists. Please Close Visit in Treatment Page",
  PRESCRIPTION_DETAILS_NOT_FOUND: "Prescription Details Not Found",
  UPLOADED_TO_S3_BUCKET_SUCCESSFULLY: "Uploaded to S3 Bucket Successfully",
  DONAR_PAYMENT_NOT_DONE: "Donar Payment Not yet Completed",
  PROVIDE_TASK_ID: "Please Provide Associate Task(Id)",
  TASK_DOES_NOT_EXIST: "Task Does Not Exist",
  TASK_COMMENT_CREATED_SUCCESSFULLY: "Comment Created Successfully",
  APPOINTMENT_RESCHEDULED_SUCCESSFULLY: "Appointment Rescheduled Successfully",
  RESCHEDULE_NOT_ALLOWED: "Reschedule Not Allowed in this Stage",
  DELETED_SUCCESSFULLY: "Deleted Successfully",
  CONSULTANT_ROASTER_NOT_FOUND: "Consultant Roaster Not Found",
  OT_PERSON_DEFAULT_EXIST: "OT Person already Added for this Role and Branch",
  OTHER_PAYMENT_ALREADY_EXISTS: "Payment Type Already Exists for this Patient",
  PROVIDE_REFERENCE_IMAGES:
    "Please provide at least one Reference Image to upload",
  REFERENCE_IMAGES_UPLOADED_SUCCESSFULLY:
    "Reference Images Uploaded Successfully",
  SUPPLIER_NAME_EXISTS: "Supplier Name Already Exists",
  PATIENTID_VISITID_REQUIRED: "Patient ID and Visit ID are required",
  PATIENT_NOT_FOUND: "Patient Not Found",
  VISIT_WITH_PATIENT_NOT_FOUND: "Visit with Patient Not Found",
  PROVIDE_HYSTEROSCOPY_ID: "Please provide Hysteroscopy ID",
  HYSTEROSCOPY_NOT_FOUND: "Hysteroscopy with given ID Not Found"
};
